apiVersion: v1
kind: Pod
metadata:
  name: user-service
  annotations:
    "consul.hashicorp.com/connect-inject": "true"
spec:
  containers:
  - name: user-service
    image: aardee/user-service-poc:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 3001
      name: http
  initContainers:
  - name: user-service-consul-init
    image: aardee/user-service-consul-init:latest
    imagePullPolicy: Always
    env:
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: HOST_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP